// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiAHDrcfVGCRePifxH_sDk2ohQkJIvI-Q',
    appId: '1:701581955889:web:655cee2d6298de32ef5610',
    messagingSenderId: '701581955889',
    projectId: 'gymai-8db8d',
    authDomain: 'gymai-8db8d.firebaseapp.com',
    storageBucket: 'gymai-8db8d.firebasestorage.app',
    measurementId: 'G-HJWVNRV72D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpFWXhmdvkI231RQCGH_VQa-3EjQg9EzU',
    appId: '1:701581955889:android:320ef40b248d9762ef5610',
    messagingSenderId: '701581955889',
    projectId: 'gymai-8db8d',
    storageBucket: 'gymai-8db8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZjh1k3UlZ7Shcb0__aXg8xiFaexbHA18',
    appId: '1:701581955889:ios:e909b4b7a0175416ef5610',
    messagingSenderId: '701581955889',
    projectId: 'gymai-8db8d',
    storageBucket: 'gymai-8db8d.firebasestorage.app',
    iosBundleId: 'com.gymai.app',
  );
}
